### ISSUE TITLE
编辑或重置配置文件时出错

### ISSUE THREAD

**Issue by starxjys** [mnixry/nonebot-plugin-gocqhttp#146]
如图
![image](https://user-images.githubusercontent.com/42333314/166657170-20ebf030-33c9-4de3-b4ba-25b35319b377.png)
![image](https://user-images.githubusercontent.com/42333314/166657262-b277da4c-2ee1-4456-8353-19f6aee886dc.png)
控制台反馈：
![image](https://user-images.githubusercontent.com/42333314/166657411-969251d3-0433-4d1b-9428-8ad6d068e3c1.png)
```
05-04 17:37:43 [INFO] uvicorn | 118.81.80.97:64072 - "DELETE /api/打码/config HTTP/1.1" 500
05-04 17:37:43 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):

  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe8b4cb2820>
           └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe8b4f4c220>
         │    └ <function MultiCommand.invoke at 0x7fe8b4cb8820>
         └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe8b4f14640>
           │               │       │       └ <function Command.invoke at 0x7fe8b4cb8310>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe8b4f14640>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe8b4edc8b0>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe8b4f14640>
           │   │      │    └ <function run at 0x7fe8aef7b1f0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe8b4cb20d0>
           └ <click.core.Context object at 0x7fe8b4f14640>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe8b2482ca0>

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe8b49d4dc0>
    └ <module 'nonebot' from '/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe8b36c50d0>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe8aedcd040>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/dist-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe8aee34af0>
    └ <uvicorn.server.Server object at 0x7fe8a6a43910>

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe8aee34b80>
           │       │   └ <uvicorn.server.Server object at 0x7fe8a6a43910>
           │       └ <function run at 0x7fe8b3fc5af0>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>

  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe8a6a3bec0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>

> File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x7fe8a6684430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c00730>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x7fe8a66844c0>
                   │   │    │      └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c00730>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
                   │   └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c00730>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fe8a6655bb0>

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c007...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
                 │    └ <fastapi.applications.FastAPI object at 0x7fe8aef88430>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fe8a6655bb0>

  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c007...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...

  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c007...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fe8aeb38f40>
          └ <fastapi.applications.FastAPI object at 0x7fe8aef88430>

  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc

  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fe8a50ed8b0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x7fe8aeb38ee0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fe8aeb38f40>

  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc

  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <fastapi.routing.APIRouter object at 0x7fe8aeb38d30>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x7fe8aeb38ee0>

  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed940>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │     └ <function Mount.handle at 0x7fe8aeb1b670>
          └ <starlette.routing.Mount object at 0x7fe8a8445580>

  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <fastapi.applications.FastAPI object at 0x7fe8a8450280>
          └ <starlette.routing.Mount object at 0x7fe8a8445580>

  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed940>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...

  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed940>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fe8a8289550>
          └ <fastapi.applications.FastAPI object at 0x7fe8a8450280>

  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc

  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fe8a50ed790>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <starlette.middleware.gzip.GZipMiddleware object at 0x7fe8a8289430>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fe8a8289550>

  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/gzip.py", line 23, in __call__
    await responder(scope, receive, send)
          │         │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fe8a50ed790>
          │         │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │         └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          └ <starlette.middleware.gzip.GZipResponder object at 0x7fe8a5c00100>

  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/gzip.py", line 42, in __call__
    await self.app(scope, receive, self.send_with_gzip)
          │    │   │      │        │    └ <function GZipResponder.send_with_gzip at 0x7fe8a82f63a0>
          │    │   │      │        └ <starlette.middleware.gzip.GZipResponder object at 0x7fe8a5c00100>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x7fe8a82893d0>
          └ <starlette.middleware.gzip.GZipResponder object at 0x7fe8a5c00100>

  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc

  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed9d0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <fastapi.routing.APIRouter object at 0x7fe8a83086d0>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x7fe8a82893d0>

  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed9d0>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │     └ <function Route.handle at 0x7fe8aeb1b040>
          └ <fastapi.routing.APIRoute object at 0x7fe8a822a8b0>

  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fe8a50ed9d0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fe8a5c...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 6789), '...
          │    └ <function request_response.<locals>.app at 0x7fe8a828dd30>
          └ <fastapi.routing.APIRoute object at 0x7fe8a822a8b0>

  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 61, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7fe8a5c00490>
                     └ <function get_request_handler.<locals>.app at 0x7fe8a828dca0>

  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7fe8b3461ee0>

  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
                 │                 │         │       └ {'process': <GoCQProcess uin=打码 password='打码' protocol=<AccountProtocol.iPad: 5> process=<subprocess.Pop...
                 │                 │         └ <function account_config_delete at 0x7fe8a82b08b0>
                 │                 └ <fastapi.dependencies.models.Dependant object at 0x7fe8a822a8e0>
                 └ <function run_in_threadpool at 0x7fe8b35498b0>

  File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
                 │     │         │        │      └ (functools.partial(<function account_config_delete at 0x7fe8a82b08b0>, process=<GoCQProcess uin=打码 password='打码...
                 │     │         │        └ <built-in method run of Context object at 0x7fe8a513a3c0>
                 │     │         └ <function run_sync at 0x7fe8b2c11c10>
                 │     └ <module 'anyio.to_thread' from '/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py'>
                 └ <module 'anyio' from '/usr/local/lib/python3.8/dist-packages/anyio/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
                 │                                        │      │                 └ False
                 │                                        │      └ (functools.partial(<function account_config_delete at 0x7fe8a82b08b0>, process=<GoCQProcess uin=打码 password='打码...
                 │                                        └ <built-in method run of Context object at 0x7fe8a513a3c0>
                 └ <function get_asynclib at 0x7fe8b2c11550>

  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
                 └ <Future finished exception=NotADirectoryError(20, 'Not a directory')>

  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
             │       │   │      └ (functools.partial(<function account_config_delete at 0x7fe8a82b08b0>, process=<GoCQProcess uin=打码 password='打码...
             │       │   └ <built-in method run of Context object at 0x7fe8a513a3c0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x7fe8a5b53640>

  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gocqhttp/web/api.py", line 134, in account_config_delete
    process.config.delete()
    │       │      └ <function AccountConfigHelper.delete at 0x7fe8a8329820>
    │       └ <nonebot_plugin_gocqhttp.process.config.AccountConfigHelper object at 0x7fe8a59f3ac0>
    └ <GoCQProcess uin=打码 password='打码' protocol=<AccountProtocol.iPad: 5> process=<subprocess.Popen object at...

  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gocqhttp/process/config.py", line 43, in delete
    self.template_path.rmdir()
    │    │             └ <function Path.rmdir at 0x7fe8b4ae7430>
    │    └ PosixPath('accounts/打码/config-template.yml')
    └ <nonebot_plugin_gocqhttp.process.config.AccountConfigHelper object at 0x7fe8a59f3ac0>

  File "/usr/lib/python3.8/pathlib.py", line 1336, in rmdir
    self._accessor.rmdir(self)
    │    │               └ PosixPath('accounts/打码/config-template.yml')
    │    └ <member '_accessor' of 'Path' objects>
    └ PosixPath('accounts/打码/config-template.yml')

NotADirectoryError: [Errno 20] Not a directory: 'accounts/打码/config-template.yml'
```
这是重设时控制台的报错

**Comment by mnixry** [comment]
已在 https://github.com/mnixry/nonebot-plugin-gocqhttp/tree/v0.5.4 中修复, 可以尝试更新以解决问题
