### ISSUE TITLE
运行nonebot时导入该模块报错

### ISSUE THREAD

**Issue by 18ghwg** [mnixry/nonebot-plugin-gocqhttp#340]
错误内容：
```
09-30 16:27:43 [ERROR] nonebot | Failed to import "nonebot_plugin_gocqhttp"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/www/server/panel/pyenv/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/www/server/panel/pyenv/lib/python3.7/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
  File "/www/server/panel/pyenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/www/server/panel/pyenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/qqbot/lib/python3.7/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/qqbot/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/www/server/panel/pyenv/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/root/qqbot/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/root/qqbot/lib/python3.7/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/qqbot/lib/python3.7/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/www/server/panel/pyenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 24, in <module>
    nonebot.load_plugin("nonebot_plugin_gocqhttp")
  File "/root/qqbot/lib/python3.7/site-packages/nonebot/plugin/load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/qqbot/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/www/server/panel/pyenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/root/qqbot/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/__init__.py", line 7, in <module>
    from . import plugin  # noqa: F401
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/plugin.py", line 8, in <module>
    from .process import ProcessesManager, RunningProcessDetail
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/process/__init__.py", line 3, in <module>
    from .manager import ProcessesManager
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/process/manager.py", line 14, in <module>
    from .process import GoCQProcess
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/process/process.py", line 17, in <module>
    from .config import generate_config, generate_device
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/process/config.py", line 9, in <module>
    from .device import random_device
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/process/device/__init__.py", line 2, in <module>
    from .generator import RandomDeviceInfoGenerator
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/process/device/generator.py", line 7, in <module>
    from .data_source import load_builds_list, load_devices_list
  File "/root/qqbot/lib/python3.7/site-packages/nonebot_plugin_gocqhttp/process/device/data_source.py", line 24, in <module>
    def load_devices_list(path: Path = DEVICES_DIR):
  File "/www/server/panel/pyenv/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

```

**Comment by 18ghwg** [comment]
试着安装其他模块，没有出现该问题，请教下大佬

**Comment by 18ghwg** [comment]
在不同的liunx服务器上测试都出现了这个问题，是我哪里没有配置吗，在win系统使用正常

**Comment by mnixry** [comment]
你是怎么装的上的? 这个插件早就不支持Python3.7了 :scream:

**Comment by 18ghwg** [comment]
晓得了，我又把版本升级到3.8搞定了&nbsp;


乐点技术论坛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月30日(星期五) 晚上7:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mnixry/nonebot-plugin-gocqhttp] 运行nonebot时导入该模块报错 (Issue #340)





 
你是怎么装的上的? 这个插件早就不支持Python3.7了 😱
