### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by H-xiaoH** [mnixry/nonebot-plugin-gocqhttp#419]
插件正常加载，在 WebUI 中进入账户信息点击 `启动` 后报错。

```text
12-14 02:00:41 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 418, in handle
    await self.app(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_gocqhttp\web\api.py", line 182, in process_start
    await process.start()
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 187, in start
    if duplicate_pid := await self._find_duplicate_process():
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 177, in _find_duplicate_process
    or self.cwd.absolute().samefile(cwd)
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1151, in samefile
    other_st = other_path.stat()
  File "C:\Users\41245\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Program Files (x86)\\Tencent\\WeChat'
```

**Comment by mnixry** [comment]
Duplicate of #401
