### ISSUE TITLE
无法通过WebUi向进程传入文字

### ISSUE THREAD

**Issue by UPON-2021** [mnixry/nonebot-plugin-gocqhttp#436]
# 环境

Python 3.10
nonebot-adapter-onebot 2.2.0
nonebot-plugin-gocqhttp 0.6.3
nonebot2 2.0.0rc2

![图片](https://user-images.githubusercontent.com/93699115/210044237-66e2c411-111a-485b-a997-6442ca3b2872.png)
![图片](https://user-images.githubusercontent.com/93699115/210044272-49e99b8a-b4ac-4a6c-92dc-b68606be5265.png)

![图片](https://user-images.githubusercontent.com/93699115/210043684-76dccff6-2e8b-46c8-82b0-684116c4ee76.png)

# 尝试:

浏览器控制台看见状态码500
![图片](https://user-images.githubusercontent.com/93699115/210043448-f300f3e0-7981-4af3-98d8-264241318011.png)
用抓包软件看了一下

![图片](https://user-images.githubusercontent.com/93699115/210043792-383963fa-a78e-411b-a6dc-407230202040.png)

控制台报错:
```
12-30 15:00:41 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\15592\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Codes\Python\CtfdBot\venv\lib\site-packages\nonebot_plugin_gocqhttp\web\api.py", line 211, in process_input_line
    process.process.stdin.write(input_)
TypeError: a bytes-like object is required, not 'str'

```

根据报错信息，在`nonebot_plugin_gocqhttp\web\api.py`的第211行尝试修改代码

![图片](https://user-images.githubusercontent.com/93699115/210043939-7b4a6b2a-de6f-41ea-84dc-1146ab5f0dba.png)

修改后状态码变为 `204`
![图片](https://user-images.githubusercontent.com/93699115/210044041-78c978b6-953f-497d-bc29-20be69762043.png)

但问题依旧，程序仍无法接收到参数
![图片](https://user-images.githubusercontent.com/93699115/210044129-676fc1be-1c6d-4fef-97d4-9d9774d06408.png)

![图片](https://user-images.githubusercontent.com/93699115/210044198-c462970e-1201-4c36-8808-268332128ba7.png)

控制台无任何报错信息

**Comment by UPON-2021** [comment]
修改代码后的控制台信息
![图片](https://user-images.githubusercontent.com/93699115/210044466-9cf4825c-d265-47b7-943e-11e1ecea2b72.png)

**Comment by mnixry** [comment]
感谢您的反馈和问题定位

请您尝试将报错的函数进行修改, 试试问题是否仍然存在

```diff
@router.post("/{uin}/process/logs", status_code=204)
async def process_input_line(
    content: models.StdinInputContent,
    process: GoCQProcess = RunningProcess(),
):
    assert process.process and process.process.stdin
    input_ = (content.input + os.linesep) if content.linesep else content.input
-   process.process.stdin.write(input_)
+  process.process.stdin.write(input_.encode())
+  process.process.stdin.flush()
```

**Comment by UPON-2021** [comment]
问题解决了

**Comment by mnixry** [comment]
~~诶等等我还没修呢, 别关~~
