### ISSUE TITLE
有点问题

### ISSUE THREAD

**Issue by TomorrowLost** [mnixry/nonebot-plugin-gocqhttp#467]
```
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 67
               └ <function _main at 0x7fe8527be5e0>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7fe85293e040>
           └ <SpawnProcess name='SpawnProcess-1' parent=2473 started>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7fe85293d670>
    └ <SpawnProcess name='SpawnProcess-1' parent=2473 started>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7fe8527d74c0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=2473 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=2473 started>
    │    └ <function subprocess_started at 0x7fe84ec7af70>
    └ <SpawnProcess name='SpawnProcess-1' parent=2473 started>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=33, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7070)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7fe8527d74f0>>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=33, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7070)>]
           │       │   │    └ <function Server.serve at 0x7fe84ec7a0d0>
           │       │   └ <uvicorn.server.Server object at 0x7fe8527d74f0>
           │       └ <function run at 0x7fe851878700>
           └ <module 'asyncio' from '/root/anaconda3/envs/nonebot2/lib/python3.9/asyncio/__init__.py'>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe84eb7fc40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fe850621940>: <Task finished name='Task-21536280' coro=<_command() done, defined at /root/anaconda3...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe82139ef70>
          │            │        │    │      └ {'_prefix': {'command': ('.bc',), 'raw_command': '.bc', 'command_arg': [MessageSegment(type='text', data={'text': 'test'})], ...
          │            │        │    └ PrivateMessageEvent(time=1674729290, self_id=1985689, post_type='message', sub_type='friend', user_id=68063855, message_type=...
          │            │        └ Bot(type='OneBot V11', self_id='1985689')
          │            └ Matcher(type='message', module=nonebot_plugin_send.notice)
          └ <function _run_matcher at 0x7fe84e8a4820>
> File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fe850621940>: <Task finished name='Task-21536280' coro=<_command() done, defined at /root/anaconda3...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe82139ef70>
          │       │   │    │      └ {'_prefix': {'command': ('.bc',), 'raw_command': '.bc', 'command_arg': [MessageSegment(type='text', data={'text': 'test'})], ...
          │       │   │    └ PrivateMessageEvent(time=1674729290, self_id=1985689, post_type='message', sub_type='friend', user_id=68063855, message_type=...
          │       │   └ Bot(type='OneBot V11', self_id='1985689')
          │       └ <function Matcher.run at 0x7fe850621670>
          └ Matcher(type='message', module=nonebot_plugin_send.notice)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fe850621940>: <Task finished name='Task-21536280' coro=<_command() done, defined at /root/anaconda3...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe82139ef70>
          │    │          │    │      └ {'_prefix': {'command': ('.bc',), 'raw_command': '.bc', 'command_arg': [MessageSegment(type='text', data={'text': 'test'})], ...
          │    │          │    └ PrivateMessageEvent(time=1674729290, self_id=1985689, post_type='message', sub_type='friend', user_id=68063855, message_type=...
          │    │          └ Bot(type='OneBot V11', self_id='1985689')
          │    └ <function Matcher.simple_run at 0x7fe8506215e0>
          └ Matcher(type='message', module=nonebot_plugin_send.notice)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
          └ Dependent(call=notice_receive)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='1985689'), 'event': PrivateMessageEvent(time=1674729290, self_id=1985689, post_type='...
                 │    │             │         │    │    └ <function notice_receive at 0x7fe8463f34c0>
                 │    │             │         │    └ Dependent(call=notice_receive)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7fe85296b550>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_send/notice.py", line 15, in notice_receive
    await bot.call_api('send_group_msg', **{
          │   └ <function Bot.call_api at 0x7fe850968f70>
          └ Bot(type='OneBot V11', self_id='1985689')
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
          └ ActionFailed(data=None, echo='738', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出')
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'message': 'test', 'group_id': 254571445}
                   │    │       │         │     └ 'send_group_msg'
                   │    │       │         └ Bot(type='OneBot V11', self_id='1985689')
                   │    │       └ <function Adapter._call_api at 0x7fe84e836b80>
                   │    └ Adapter(name='OneBot V11')
                   └ Bot(type='OneBot V11', self_id='1985689')
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
           │                       │    │             │     │    └ 30.0
           │                       │    │             │     └ 738
           │                       │    │             └ <function ResultStore.fetch at 0x7fe84e8368b0>
           │                       │    └ <nonebot.adapters.onebot.store.ResultStore object at 0x7fe84e83b250>
           │                       └ Adapter(name='OneBot V11')
           └ <function handle_api_result at 0x7fe84e92a8b0>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': '738', 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhttp 端输出'}
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='738', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出')
```

**Comment by mnixry** [comment]
> 请参考 go-cqhttp 端输出

问题和本插件无关

**Comment by TomorrowLost** [comment]
> 

这么快回应，这效率

**Comment by mnixry** [comment]
> 这么快回应，这效率

~~我住在GitHub~~

**Comment by mnixry** [comment]
那就是被风控了……这个东西很玄学

https://github.com/Mrs4s/go-cqhttp/issues?q=%E9%A3%8E%E6%8E%A7+sort%3Acomments-desc

再说一次…… 这个问题很显然不是这个插件的…… 风控是腾讯的问题和谁都没关系
