### ISSUE TITLE
在Startup函数出现错误导致nonebot整体崩溃

### ISSUE THREAD

**Issue by LinkTechElectric** [mnixry/nonebot-plugin-gocqhttp#468]
环境：Ubuntu Desktop 20.04 LTS
Python版本：3.8.10
错误复现：
```
01-27 01:31:52 [SUCCESS] nonebot | NoneBot is initializing...
01-27 01:31:52 [INFO] nonebot | Current Env: dev
01-27 01:31:52 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('192.168.31.7'), 'port': 11451, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'dev'}
01-27 01:31:52 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
01-27 01:31:52 [DEBUG] nonebot | Succeeded to load adapter "OneBot V12"
01-27 01:31:52 [DEBUG] nonebot | Succeeded to load adapter "ntchat"
01-27 01:31:52 [DEBUG] nonebot | Succeeded to load adapter "Spigot"
01-27 01:31:52 [SUCCESS] nonebot | Succeeded to import "echo"
01-27 01:31:54 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
01-27 01:31:54 [SUCCESS] nonebot | Running NoneBot...
01-27 01:31:54 [DEBUG] nonebot | Loaded adapters: OneBot V11, OneBot V12, ntchat, Spigot
01-27 01:31:54 [INFO] uvicorn | Will watch for changes in these directories: ['/home/linkjune/app/bot/qq/LynerBot']
01-27 01:31:54 [INFO] uvicorn | Uvicorn running on http://192.168.31.7:11451 (Press CTRL+C to quit)
01-27 01:31:54 [INFO] uvicorn | Started reloader process [2731531] using watchgod
01-27 01:31:55 [SUCCESS] nonebot | NoneBot is initializing...
01-27 01:31:55 [INFO] nonebot | Current Env: dev

01-27 01:31:57 [INFO] uvicorn | Started server process [2731556]
01-27 01:31:57 [INFO] uvicorn | Waiting for application startup.
01-27 01:31:57 [INFO] nonebot_plugin_apscheduler | Scheduler Started
01-27 01:31:57 [INFO] nonebot_plugin_gocqhttp | Begin to Download binary from https://download.fastgit.org/Mrs4s/go-cqhttp/releases/latest/download/go-cqhttp_linux_amd64.tar.gz
01-27 01:31:59 [ERROR] nonebot_plugin_gocqhttp | An error has been caught in function 'startup', process 'SpawnProcess-1' (2731556), thread 'MainThread' (140045317609280):
Traceback (most recent call last):
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 169, in _receive_event
    event = self._h11_state.next_event()
  File "/home/linkjune/.local/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/home/linkjune/.local/lib/python3.8/site-packages/h11/_connection.py", line 375, in _extract_next_receive_event
    event = self._reader.read_eof()
  File "/home/linkjune/.local/lib/python3.8/site-packages/h11/_readers.py", line 117, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (received 130256 bytes, expected 4889604)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 239, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 346, in __aiter__
    async for part in self._stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 295, in __aiter__
    raise exc
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 288, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 160, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 169, in _receive_event
    event = self._h11_state.next_event()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (received 130256 bytes, expected 4889604)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/linkjune/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/linkjune/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/linkjune/.local/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 84, in main
    await app(scope, self.receive, self.send)
  File "/home/linkjune/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/linkjune/.local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/routing.py", line 645, in __call__
    await self.lifespan(scope, receive, send)
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/routing.py", line 598, in startup
    await handler()
> File "/home/linkjune/.local/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/__init__.py", line 32, in startup
    await download_gocq()
  File "/home/linkjune/.local/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/download.py", line 63, in download_gocq
    async for chunk in response.aiter_bytes():
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_models.py", line 1680, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_models.py", line 1734, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_client.py", line 145, in __aiter__
    async for chunk in self._stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 240, in __aiter__
    yield part
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (received 130256 bytes, expected 4889604)
01-27 01:31:59 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 169, in _receive_event
    event = self._h11_state.next_event()
  File "/home/linkjune/.local/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/home/linkjune/.local/lib/python3.8/site-packages/h11/_connection.py", line 375, in _extract_next_receive_event
    event = self._reader.read_eof()
  File "/home/linkjune/.local/lib/python3.8/site-packages/h11/_readers.py", line 117, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (received 130256 bytes, expected 4889604)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 239, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 346, in __aiter__
    async for part in self._stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 295, in __aiter__
    raise exc
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 288, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 160, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 169, in _receive_event
    event = self._h11_state.next_event()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (received 130256 bytes, expected 4889604)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/home/linkjune/.local/lib/python3.8/site-packages/starlette/routing.py", line 598, in startup
    await handler()
  File "/home/linkjune/.local/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/__init__.py", line 32, in startup
    await download_gocq()
  File "/home/linkjune/.local/lib/python3.8/site-packages/loguru/_logger.py", line 1212, in catch_wrapper
    return await function(*args, **kwargs)
  File "/home/linkjune/.local/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/download.py", line 63, in download_gocq
    async for chunk in response.aiter_bytes():
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_models.py", line 1680, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_models.py", line 1734, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_client.py", line 145, in __aiter__
    async for chunk in self._stream:
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 240, in __aiter__
    yield part
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linkjune/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (received 130256 bytes, expected 4889604)

01-27 01:31:59 [ERROR] uvicorn | Application startup failed. Exiting.
^C01-27 01:37:02 [INFO] uvicorn | Stopping reloader process [2731531]
```

**Comment by mnixry** [comment]
请更新您的本插件到最新版本，理论上已经解决了

**Comment by mnixry** [comment]
Duplicate of #385
