### ISSUE TITLE
用nonebot安装后运行出现提示无法下载镜像？

### ISSUE THREAD

**Issue by sherlockHlb** [mnixry/nonebot-plugin-gocqhttp#485]
02-09 18:54:37 [ERROR] logging | Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NBBOOT\bot2\.venv\Lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\Desktop\NBBOOT\bot2\.venv\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\Desktop\NBBOOT\bot2\.venv\Lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\NBBOOT\bot2\.venv\Lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 41, in startup
    await download_gocq()
  File "C:\Users\Administrator\Desktop\NBBOOT\bot2\.venv\Lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 120, in download_gocq
    raise RuntimeError("No available download mirror found.")
RuntimeError: No available download mirror found.

02-09 18:54:37 [ERROR] logging | Application startup failed. Exiting.

**Comment by mnixry** [comment]
~~网太差了，换个环境试试~~

**Comment by sherlockHlb** [comment]
腾讯的云服务器,换了清华大学的源=.=

**Comment by sherlockHlb** [comment]
腾讯云的服务器，如何更换

**Comment by mnixry** [comment]
理论上提供的这些镜像总该有个能用的，你这个情况太罕见了……（能用的镜像我都内置了，这个要的不是PyPI镜像）

**Comment by wyh0106** [comment]
> 

我是国外的VPS服务器，同样出现了这个问题，真是奇了怪了，可以自己去go-cqhttp上下载二进制文件，放进自己创建的binary文件夹里吗？

**Comment by wyh0106** [comment]
`PermissionError: [Errno 13] Permission denied: 'accounts/binary'`
我还出现了这个报错

**Comment by mnixry** [comment]
> `PermissionError: [Errno 13] Permission denied: 'accounts/binary'` 我还出现了这个报错

@wyh0106 字面意思。这个问题和网络连接无关。

**Comment by X-Skirt-X** [comment]
我也同样遇到了这个问题,请问可以直接自己手动下载吗?貌似自己直接下载放进binary文件夹行不通

**Comment by liufuxing** [comment]
同遇到这个问题，请问有人解决了吗

**Comment by wyh0106** [comment]
> 同遇到这个问题，请问有人解决了吗
我解决了，不过我不是因为网络的问题。如果你出现形如`PermissionError: [Errno 13] Permission denied: 'accounts/binary'`的报错那就应该是遇到和我一养的问题了。
这个其实是你用的FTP上传的文件夹是只读格式，我用termius就有这个问题，换成mobaxtern就没这个问题了。

**Comment by X-Skirt-X** [comment]
> > 同遇到这个问题，请问有人解决了吗
> > 我解决了，不过我不是因为网络的问题。如果你出现形如`PermissionError: [Errno 13] Permission denied: 'accounts/binary'`的报错那就应该是遇到和我一养的问题了。
> > 这个其实是你用的FTP上传的文件夹是只读格式，我用termius就有这个问题，换成mobaxtern就没这个问题了。


termius有办法让文件不是只读格式吗?

**Comment by X-Skirt-X** [comment]
> > 同遇到这个问题，请问有人解决了吗
> > 我解决了，不过我不是因为网络的问题。如果你出现形如`PermissionError: [Errno 13] Permission denied: 'accounts/binary'`的报错那就应该是遇到和我一养的问题了。
> > 这个其实是你用的FTP上传的文件夹是只读格式，我用termius就有这个问题，换成mobaxtern就没这个问题了。

termius可以修改文件权限,右键文件可以看见

**Comment by Zwc84** [comment]
关于这个问题我通过手动修改binary文件夹内的go-cqhttp(服务器相对应的版本)再通过WinSCP修改go cq的文件属性777解决了这个问题
