### ISSUE TITLE
python从3.8更换3.9插件加载失败了

### ISSUE THREAD

**Issue by njgaoweiting** [mnixry/nonebot-plugin-gocqhttp#642]
06-16 11:13:47 [ERROR] nonebot | Failed to import "nonebot_plugin_gocqhttp"
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "d:\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "d:\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "d:\python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "d:\python\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "d:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\CirnoBot\njgwt-bot\.\bot.py", line 24, in <module>
    nonebot.load_plugin("nonebot_plugin_gocqhttp")
  File "d:\python\lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
> File "d:\python\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "d:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "d:\python\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\python\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 9, in <module>
    import nonebot_plugin_gocqhttp.plugin  # noqa: F401
  File "d:\python\lib\site-packages\nonebot_plugin_gocqhttp\plugin.py", line 8, in <module>
    from .process import ProcessesManager, RunningProcessDetail
  File "d:\python\lib\site-packages\nonebot_plugin_gocqhttp\process\__init__.py", line 2, in <module>
    from .download import BINARY_DIR, BINARY_PATH, download_gocq
  File "d:\python\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 16, in <module>
    from nonebot_plugin_gocqhttp.process.platform import (
  File "d:\python\lib\site-packages\nonebot_plugin_gocqhttp\process\platform.py", line 3, in <module>
    import psutil
  File "d:\python\lib\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "d:\python\lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ModuleNotFoundError: No module named 'psutil._psutil_windows'
06-16 11:13:47 [SUCCESS] nonebot | Running NoneBot...
06-16 11:13:47 [INFO] uvicorn | Started server process [15980]
06-16 11:13:47 [INFO] uvicorn | Waiting for application startup.
06-16 11:13:47 [INFO] uvicorn | Application startup complete.
06-16 11:13:47 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:22333 (Press CTRL+C to quit)
06-16 11:13:56 [INFO] uvicorn | 127.0.0.1:9233 - "GET /go-cqhttp/ HTTP/1.1" 404

**Comment by mnixry** [comment]
升级Python版本要把依赖的库重新安装一遍，直接复制粘贴旧文件行不通。
