### ISSUE TITLE
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

### ISSUE THREAD

**Issue by LiShenshun** [mnixry/nonebot-plugin-gocqhttp#656]
用nb plugin install nonebot-plugin-gocqhttp 指令安装的 0.6.10 版本，web登陆后无法自动刷新，控制台报错
```
07-01 21:56:07 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/docker/nb2-test/venv/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/routing.py", line 283, in app
    solved_result = await solve_dependencies(
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 593, in solve_dependencies
    solved_result = await solve_dependencies(
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
    solved = await call(**sub_values)
TypeError: __call__() missing 1 required positional argument: 'request'
07-01 21:56:07 [INFO] websockets | connection open
07-01 21:56:07 [ERROR] websockets | closing handshake failed
Traceback (most recent call last):
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 248, in handler
    await self.close()
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/docker/nb2-test/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
07-01 21:56:07 [INFO] websockets | connection closed
```

尝试用[227ef89](https://github.com/mnixry/nonebot-plugin-gocqhttp/commit/227ef890cce5d31b74def2c5fe679851c86a76b2)源码安装，quasar build 报错

```
[5/5] Building fresh packages...
success Saved 0 new dependencies.
 app:quasar-conf Reading quasar.conf.js +4s

⚠️  Quasar CLI requires a minor change to the root component:
   E:\Code\test2\nonebot-plugin-gocqhttp\frontend\src\App.vue

  Please add: id="q-app" (or write #q-app if using Pug)
  to the outermost HTML element of the template.

Example:
  <template>
    <div id="q-app">
      ...
    </div>
  </template>

error Command failed with exit code 1.
```

以上两种情况在之前装的旧版没有出现

**Comment by mnixry** [comment]
检查一下你本地的fastapi版本

**Comment by LiShenshun** [comment]
fastapi                 0.99.0
这个环境是用nb-cli引导构建的。

源码构建那边用的poetry install的，因为web无法构建所以没继续往下测试了

**Comment by mnixry** [comment]
我不理解.jpg 感觉是FastAPI的问题，报错堆栈没有我这边的东西

**Comment by LiShenshun** [comment]
把fastapi 降级到0.92.0 好了（不确定其他版本，只是我一个之前的环境）

另外源码web的quasar build能修吗？

**Comment by mnixry** [comment]
有CI的，编译肯定没问题：https://github.com/mnixry/nonebot-plugin-gocqhttp/actions/runs/5407832657/jobs/9826270313

你这个报错应该是操作不对（？

**Comment by EmiyaGm** [comment]
> 把fastapi 降级到0.92.0 好了（经过测试，目前只能到0.96.0，再高就开始报同样的错误）
> 
> 另外源码web的quasar build能修吗？

相同的问题，借楼问一下如何降低内置的 fastapi 版本

**Comment by mnixry** [comment]
fixed in https://github.com/mnixry/nonebot-plugin-gocqhttp/commit/edf3ca5957efc7d717e825560443c37f2e2d4b7d
